# 데이터 전처리 실습

## 1. 필요 패키지(모듈) 임포트

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
# 한글 폰트 설정
import matplotlib.font_manager as fm
font_path = "C:\\Windows\\Fonts\\나눔고딕코딩.ttf"
fontprop = fm.FontProperties(fname=font_path)
plt.rcParams['font.family'] = fontprop.get_name()
plt.rcParams['axes.unicode_minus'] = False # 마이너스 기호 깨짐 방지

## 2. 데이터 수집 (데이터 읽어오기)

In [3]:
test_df = pd.read_csv('practice.csv')
test_df

,ID,Age,Height,Weight,Score1,Score2,Score3,Income,Expenses,Satisfaction
0,1,50.0,174.0,NaN,NaN,69.0,94,98615,36333,8.0
1,2,34.0,NaN,93.0,90.0,75.0,87,93480,45913,NaN
2,3,38.0,171.0,71.0,65.0,64.0,79,61314,36033,7.0
3,4,33.0,174.0,98.0,66.0,95.0,60,73754,23796,4.0
4,5,22.0,181.0,91.0,100.0,92.0,64,75554,18847,8.0
...,...,...,...,...,...,...,...,...,...,...
95,96,32.0,169.0,57.0,72.0,65.0,72,85991,14297,NaN
96,97,24.0,189.0,74.0,90.0,99.0,79,43762,35947,3.0
97,98,41.0,152.0,70.0,89.0,65.0,69,45827,17347,NaN
98,99,50.0,178.0,94.0,81.0,87.0,89,34749,13166,4.0
99,100,38.0,185.0,67.0,89.0,91.0,100,48806,37480,6.0

In [4]:
# 데이터 구조 파악
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            100 non-null    int64
 1   Age           97 non-null     float64
 2   Height        97 non-null     float64
 3   Weight        98 non-null     float64
 4   Score1        93 non-null     float64
 5   Score2        98 non-null     float64
 6   Score3        100 non-null    int64
 7   Income        100 non-null    int64
 8   Expenses      100 non-null    int64
 9   Satisfaction  94 non-null     float64
dtypes: float64(6), int64(4)
memory usage: 7.9 KB

In [5]:
# 결측치 확인
test_df.isnull().sum()

ID              0
Age             3
Height          3
Weight          2
Score1          7
Score2          2
Score3          0
Income          0
Expenses        0
Satisfaction    6
dtype: int64

In [6]:
# 결측률 측정
(test_df.isnull().mean())

ID              0.00
Age             0.03
Height          0.03
Weight          0.02
Score1          0.07
Score2          0.02
Score3          0.00
Income          0.00
Expenses        0.00
Satisfaction    0.06
dtype: float64

In [7]:
# 결측지 삭제(행)
test_df_drop_na = test_df.dropna()
test_df_drop_na

,ID,Age,Height,Weight,Score1,Score2,Score3,Income,Expenses,Satisfaction
2,3,38.0,171.0,71.0,65.0,64.0,79,61314,36033,7.0
3,4,33.0,174.0,98.0,66.0,95.0,60,73754,23796,4.0
4,5,22.0,181.0,91.0,100.0,92.0,64,75554,18847,8.0
5,6,29.0,195.0,69.0,76.0,75.0,70,87942,48946,5.0
6,7,37.0,174.0,60.0,87.0,87.0,79,50399,46377,1.0
...,...,...,...,...,...,...,...,...,...,...
93,94,21.0,160.0,54.0,78.0,96.0,84,69263,19019,6.0
94,95,23.0,197.0,74.0,72.0,76.0,86,90224,40340,3.0
96,97,24.0,189.0,74.0,90.0,99.0,79,43762,35947,3.0
98,99,50.0,178.0,94.0,81.0,87.0,89,34749,13166,4.0
99,100,38.0,185.0,67.0,89.0,91.0,100,48806,37480,6.0

In [11]:
# 결측지 삭제 (열(컬럼))
test_df_drop_col = test_df.drop(columns=['Score1'])
test_df_drop_col

     ID   Age  Height  Weight  Score2  Score3  Income  Expenses  Satisfaction
0     1  50.0   174.0     NaN    69.0      94   98615     36333           8.0
1     2  34.0     NaN    93.0    75.0      87   93480     45913           NaN
2     3  38.0   171.0    71.0    64.0      79   61314     36033           7.0
3     4  33.0   174.0    98.0    95.0      60   73754     23796           4.0
4     5  22.0   181.0    91.0    92.0      64   75554     18847           8.0
..  ...   ...     ...     ...     ...     ...     ...       ...           ...
95   96  32.0   169.0    57.0    65.0      72   85991     14297           NaN
96   97  24.0   189.0    74.0    99.0      79   43762     35947           3.0
97   98  41.0   152.0    70.0    65.0      69   45827     17347           NaN
98   99  50.0   178.0    94.0    87.0      89   34749     13166           4.0
99  100  38.0   185.0    67.0    91.0     100   48806     37480           6.0

[100 rows x 9 columns]

In [13]:
# 걸측지 대체 (중앙값)
test_df_fillna = test_df.copy()
test_df_fillna['Score1'] = test_df_fillna['Score1'].fillna(
    test_df_fillna['Score1'].median().round()
)

test_df_fillna

,ID,Age,Height,Weight,Score1,Score2,Score3,Income,Expenses,Satisfaction
0,1,50.0,174.0,NaN,82.0,69.0,94,98615,36333,8.0
1,2,34.0,NaN,93.0,90.0,75.0,87,93480,45913,NaN
2,3,38.0,171.0,71.0,65.0,64.0,79,61314,36033,7.0
3,4,33.0,174.0,98.0,66.0,95.0,60,73754,23796,4.0
4,5,22.0,181.0,91.0,100.0,92.0,64,75554,18847,8.0
...,...,...,...,...,...,...,...,...,...,...
95,96,32.0,169.0,57.0,72.0,65.0,72,85991,14297,NaN
96,97,24.0,189.0,74.0,90.0,99.0,79,43762,35947,3.0
97,98,41.0,152.0,70.0,89.0,65.0,69,45827,17347,NaN
98,99,50.0,178.0,94.0,81.0,87.0,89,34749,13166,4.0
99,100,38.0,185.0,67.0,89.0,91.0,100,48806,37480,6.0